- op: replace
  path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
  value: platform-uat
- op: replace
  path: /metadata/annotations/alb.ingress.kubernetes.io~1certificate-arn
  value: arn:aws:acm:eu-west-1:918780499156:certificate/32678114-e8a2-4908-b31a-7a7cde719332
- op: replace
  path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
  value: origin-weather-uat.cloud-master-ai.com
- op: add
  path: /metadata/annotations/alb.ingress.kubernetes.io~1group.order
  value: "15"
- op: replace
  path: /spec/rules/0/host
  value: origin-weather-uat.cloud-master-ai.com
