apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-air-quality-api-development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development
  source:
    repoURL: https://github.com/amohsenter09-github/weather-api-fastapi.git
    targetRevision: master
    path: air-quality-api/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: air-quality-api-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
