apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: air-quality-api-uat

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: air-quality-api
    path: deployment-image.patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: air-quality-api
    path: ingress-hostname.patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: air-quality-api
    path: rbac-rolebinding-patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: NetworkPolicy
      name: air-quality-api-ingress
    path: networkpolicy-ingress-patch.yaml
