apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: air-quality-api

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: air-quality-api
    path: ingress-group.patch.yaml
