apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-weather-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/amohsenter09-github/weather-api-fastapi.git
    targetRevision: master
    path: k8s-eks/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
