apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-api
  namespace: weather-api
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: "200"

    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:918780499156:certificate/589630d4-3d47-4f4d-9fb2-ad2cbf586011
    alb.ingress.kubernetes.io/ssl-redirect: "443"

    external-dns.alpha.kubernetes.io/hostname: origin-weather.cloud-master-ai.com

    # CloudFront-only lockdown (from Terraform output alb_cloudfront_only_security_group_id)
    alb.ingress.kubernetes.io/security-groups: sg-03282d61a563152d4
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
spec:
  ingressClassName: alb
  rules:
    - host: origin-weather.cloud-master-ai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weather-api
                port:
                  number: 80